### PR TITLE
Cleanup/legos

### PR DESCRIPTION
**Pull request by tinnakaren**
Working on cleaning up legos to make it simpler to integrate it in themes.

### CODE REVIEW

**Comment by jsergiu** [comment]
OK

**Comment by haukurmar** [comment]
LIKE

**Comment by haukurmar** [comment]
Did you clean up all variable naming conventions like you did in the heading lego or do we have something left in that area?

**Comment by tinnakaren** [comment]
I’m going to clean up all variables also, but I only started picking up on it for headings, so I’m going to go back and do these legos again and see if I missed something.

**Comment by haukurmar** [comment]
I've commented in two places, just what I saw right away without much time to look at it.
You can see it in your email probably

**Comment by haukurmar** [comment]
Are we ready for merge here?

**Comment by jsergiu** [comment]
Ok for me. if you reviewed the code I think you can just merge.

**Pull request merged**
